#! /bin/sh

# start sxhdk
pgrep -x sxhkd > /dev/null || sxhkd &

# start polybar
$HOME/.config/polybar/launch.sh

# start feh
feh --bg-fill $HOME/Pictures/mountain.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config active_border_color \#88c0d0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
