#! /bin/sh

# start sxhdk
pgrep -x sxhkd > /dev/null || sxhkd &

# start polybar
$HOME/.config/polybar/launch.sh

# start feh
feh --bg-fill $HOME/Pictures/wallpaper.jpg

picom --no-use-damage

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on