fork = true

[font]
normal = { family = "Cascadia Mono NF", style = "Regular" }
italic = { family = "Cascadia Mono NF", style = "Italic" }
size = 12

[font.features]
"Cascadia Mono NF" = [ "+salt", "+zero" ]
