export PATH=$HOME/.cargo/bin:$PATH:$HOME/.local/bin:$HOME/go/bin
export LANG=en_US.UTF-8
export TZ=America/New_York
export EDITOR=nvim
export TOOLBOX_SHELL=$(which zsh)

# Use clang as default C/C++ compiler
export CC=clang
export CXX=clang++
export CMAKE_GENERATOR=Ninja

# opam configuration
[[ ! -r /home/michael/.opam/opam-init/init.zsh ]] || source /home/michael/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

