[general]
import = [
  "~/.config/alacritty/modus_vivendi.toml"
]

[window]
dimensions = { columns = 172, lines = 54 }
dynamic_title = false

[font]
size = 11
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
