[general]
import = [
  "~/.config/alacritty/modus_vivendi.toml"
]

[window]
dimensions = { columns = 130, lines = 42 }
dynamic_title = false

[font]
size = 10
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }

[terminal]
shell = "/usr/bin/nu"
