[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 130, lines = 42 }
dynamic_title = false

[font]
size = 11
normal = { family = "CaskaydiaMono Nerd Font Propo", style = "Regular" }
